### ISSUE TITLE
README & color-ops

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-color-operations#1]
I fear I may have inceptioned this repo https://github.com/mapbox/color-ops/

**Comment by lbud** [comment]
@tmcw … :| 
um
but I can do the README, but… what are your thoughts on this?

**Comment by tmcw** [comment]
Err, I had implemented that in https://github.com/mapbox/color-ops a week+ ago https://github.com/mapbox/color-ops/commit/01f3045096adb073df5b1ecbb695a37b6a932a59 - so we just reached 100% work duplication :|

Fwiw I think color-ops is closer to complete that this repo, for a bunch of reasons - the code style here is wrong, tests are incomplete, parseCSSColor shouldn't be a dependency on this level, etc.

**Comment by lbud** [comment]
ok welp next time I propose we sprint on either mind-reading or communication because

.

**Comment by tmcw** [comment]
color-ops is what app-styles used when we did color transformations, and generally I search `npm` and the `mapbox` organization before creating any repo. I'll re-enable my auto-subscribe github notifications to try to catch stuff like this earlier.
